# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure(2) do |config|
  config.vm.box = "hashicorp/precise32"

  config.vm.network "forwarded_port", guest: 80, host: 80
  config.vm.network "forwarded_port", guest: 9999, host:9999

  config.vm.provision "shell", inline: <<-SHELL
     sudo apt-get update
     sudo apt-get install -y nginx
     debconf-set-selections <<< 'mysql-server mysql-server/root_password password temporary_password'
     debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password temporary_password'
     sudo apt-get install -y mysql-server

     apt-get install -y build-essential
     
     wget https://www.python.org/ftp/python/3.4.3/Python-3.4.3.tgz
     tar -xvf Python-3.4.3.tgz
     cd Python-3.4.3
     ./configure
     make
     make test
     sudo make install
     sudo apt-get install python3-pip
     sudo pip3 install flask
     sudo pip3 install uwsgi
   SHELL
end
