# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "forwarded_port", guest: 80, host: 80

  config.vm.provision "shell", inline: <<-SHELL
     sudo apt-get update
     sudo apt-get install -y nginx
     debconf-set-selections <<< 'mysql-server mysql-server/root_password password temporary_password'
     debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password temporary_password'
     sudo apt-get install -y mysql-server
     sudo apt-get install -y python3-pip
     sudo pip3 install flask
     sudo pip3 install uwsgi
   SHELL
end
